- hosts: ceos
  gather_facts: no
  connection: local

  tasks:
  - name: Register SSH key for each host
    command: ssh-keyscan {{ inventory_hostname | lower }}
    register: keyscan

  - name: Delete existing known_hosts file
    file:
      path: ~/.ssh/known_hosts
      state: absent

  - name: Add SSH keys to known_hosts
    lineinfile:
      name: ~/.ssh/known_hosts
      create: yes
      line: '{{ item }}'
    loop: '{{ keyscan.stdout_lines }}'